### PR TITLE
richard-random-fixes-2

### LINKED ISSUE #200: Change "Share" Buttons to "Tweet" and have it open a Twitter Intent Page

### LINKED ISSUE #239: combine input field heights with non-native select component -  simple fix for MVP
just think to have a pragmatic fix for demo of the combination of  input + select component is to apply a  h-16 class

see top is after change ( did it in chrome inspector )  
see bottom - is the "bug"  

Bildschirmfoto 2021-09-15 um 13 15 52

but i still think it would be better to change to native select because mobile devices handle this better - after mvp

### PR DESCRIPTION
**Pull request by scco**
### inputs + nonnative select quick fix

Bildschirmfoto 2021-09-15 um 13 15 52

- temporary fix for height issues when combining native inputs with non-native selects
( top = after .  bottom = before )
Closes #239

### tweets for grant detail view, round detail view, cart view

Bildschirmfoto 2021-09-15 um 15 09 46

- add working rudimentary tweet buttons  that share
"Checkout {round or grant} at Gitcoins Decentral Grants App!"
+ a generated encoded Link to https://grants.gtcdao.net + route to a specific grant / round

Closes #200

### notification styling

https://user-images.githubusercontent.com/569641/133439774-5e369c3c-b8ef-45e3-ac36-fc4c27a7319d.mov

- styling as good as i can this bn-notify addon,
whats not very stylable ( eg i can not set a better width for a notification )

came up with the idea this notifications show "behind the scenes" as a mini terminal,
as this shows so cryptic stuff all the time right now ^^ + i think our audience 
is technical versatile and love terminals too.

ps : that plugin is hard to style - can not even change width because that transitions to the right on hide i guess

### CODE REVIEW

File: app/src/views/GrantRegistryGrantDetail.vue [hunk 1]
```diff
@@ -284,7 +298,7 @@ import TransactionStatus from 'src/components/TransactionStatus.vue';
 import LoadingSpinner from 'src/components/LoadingSpinner.vue';
 import { CLR, fetch, InitArgs, linear } from '@dgrants/dcurve';
 // --- Icons ---
-import { ArrowToprightIcon as ShareIcon } from '@fusion-icons/vue/interface';
+import { TwitterIcon as TwitterIcon } from '@fusion-icons/vue/interface';
```
Comment (thelostone-mc) [inline app/src/views/GrantRegistryGrantDetail.vue:301]:
```suggestion
import { TwitterIcon } from '@fusion-icons/vue/interface';
```

**Review by thelostone-mc — APPROVED** [review]
@scco left one tiny comment ! LGTM

File: app/src/views/GrantRegistryGrantDetail.vue (hunk 1 above)
Comment (scco) [reply app/src/views/GrantRegistryGrantDetail.vue]: pushed right now removing in 2 files the unnessesary "as TwitterIcon"

**Comment by scco** [comment]
talked with graham - we go for this for now .

**Review by mds1 — APPROVED** [review]
