### PR TITLE
fix logo updating

### LINKED ISSUE #580: Grants logo change is not working
When editing grants logo, the newly uploaded logo isn't displaying, despite seeing successful transactions

### LINKED ISSUE #583: Use Placeholder image in edit form when logo is not set
When there is no logo, image path in edit form is `https://scopelift.b-cdn.net/ipfs/` and shows that as logoURI
Screen Shot 2021-12-08 at 10 22 17 PM

### PR DESCRIPTION
**Pull request by mk1r**
resolves #580 and resolves #583

to test: try changing logo (using the edit form), and the previous logo is still showing up, see it fixed when testing this branch

### CODE REVIEW

File: app/src/components/BaseImageUpload.vue [hunk 1]
```diff
@@ -46,7 +46,7 @@
 
       <!-- filename -->
       <div class="col-span-6 md:col-span-4 mb-3 md:mb-0 truncate">
-        {{ logoURI }}
+        {{ logoURI !== '/placeholder_grant.svg' ? logoURI : 'placeholder_grant.svg' }}
```
Comment (gdixon) [inline app/src/components/BaseImageUpload.vue:49]: should the falsy branch be prefixed with a `/`?

File: app/src/views/GrantRegistryGrantDetail.vue [hunk 2]
```diff
@@ -649,7 +653,10 @@ function useGrantDetail() {
     form.value.payee = grant.value?.payee || '';
     form.value.name = grantMetadata.value?.name || '';
     form.value.description = grantMetadata.value?.description || '';
-    form.value.logoURI = ipfs.getMetaPtr({ cid: grantMetadata.value?.logoPtr?.pointer }) || undefined;
+    form.value.logoURI =
+      ipfs.getMetaPtr({ cid: grantMetadata.value?.logoPtr?.pointer }) !== 'https://scopelift.b-cdn.net/ipfs/'
+        ? ipfs.getMetaPtr({ cid: grantMetadata.value?.logoPtr?.pointer })
+        : '/placeholder_grant.svg';
```
Comment (gdixon) [inline app/src/views/GrantRegistryGrantDetail.vue:659]: Instead of hardcoding `https://scopelift.b-cdn.net/ipfs/` - could we just check if `grantMetadata.value?.logoPtr?.pointer` holds a value:

```suggestion

    const cid = grantMetadata.value?.logoPtr?.pointer;
    form.value.logoURI = cid ? ipfs.getMetaPtr({ cid }) : '/placeholder_grant.svg';
```

**Review by gdixon — CHANGES_REQUESTED** [review]
This works great @mk1r, nice job! Just one question and a little nitpick!

File: app/src/components/BaseImageUpload.vue (hunk 1 above)
Comment (mk1r) [reply app/src/components/BaseImageUpload.vue:49]: I'm not sure if it needs to be, it was working find without `/` but was worried it could break in prod - what are your thoughts?

File: app/src/views/GrantRegistryGrantDetail.vue (hunk 2 above)
Comment (mk1r) [reply app/src/views/GrantRegistryGrantDetail.vue:659]: yeah that's better

File: app/src/components/BaseImageUpload.vue (hunk 1 above)
Comment (gdixon) [reply app/src/components/BaseImageUpload.vue]: Ahhh this is only used to display the filename - yeah we don't need it (the `/`)!

File: app/src/views/GrantRegistryGrantDetail.vue [hunk 3]
```diff
@@ -649,7 +653,8 @@ function useGrantDetail() {
     form.value.payee = grant.value?.payee || '';
     form.value.name = grantMetadata.value?.name || '';
     form.value.description = grantMetadata.value?.description || '';
-    form.value.logoURI = ipfs.getMetaPtr({ cid: grantMetadata.value?.logoPtr?.pointer }) || undefined;
+    const cid = grantMetadata.value?.logoPtr?.pointer;
```
Comment (gdixon) [inline app/src/views/GrantRegistryGrantDetail.vue:656]: I'd personally move this above the `form.value.*` defs - but it's fine where it is!

**Review by gdixon — APPROVED** [review]
Awesome job @mk1r!

**Review by thelostone-mc — APPROVED** [review]
